name: Node CI

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - '*'

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest]
                node-version: [18.17.1]
        runs-on: ${{ matrix.platform }}
        env:
            PUPPETEER_SKIP_DOWNLOAD: true
            CI: false
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - run: yarn install

            - run: yarn build
